#!/bin/bash

# This is a post-checkout hook that runs after switching branches.
# The following steps rebuild the shared library and install dependencies in the app and cms.

function install_shared () {
        echo "Syncing shared library with branch"

        echo "Building the shared library..."
        cd ./shared || exit
        npm run build || exit

        echo "Installing dependencies in the app..."
        cd ../app || exit
        npm ci --install-links || exit

        echo "Installing dependencies in the cms..."
        cd ../cms || exit
        npm ci --install-links || exit

        echo "Sync complete, happy coding!"
}

# Allows us to read user input below, assigns stdin to keyboard
exec < /dev/tty

while true; do
    read -p "Do you want to re-build and install the shared library? " yn
    case $yn in
        [Yy]* ) install_shared; break;; 
        [Nn]* ) exit;;
        * ) echo "Please answer yes or no.";;
    esac
done
