#!/bin/bash

# This is a post-checkout hook that runs after switching branches.
# The following steps rebuild the shared library and install dependencies in the app and cms.

echo "Syncing shared library with branch"

echo "Building the shared library..."
cd ./shared || exit
npm run build || exit

echo "Installing dependencies in the app..."
cd ../app || exit
npm ci --install-links || exit

echo "Installing dependencies in the cms..."
cd ../cms || exit
npm ci --install-links || exit

echo "Sync complete, happy coding!"
