import { DbService } from "../db.service";
import { DeleteReason, DocType } from "../../enums";

/**
 * Upgrade the database schema from version 10 to 11
 * Backfill the language field on DeleteCmd documents generated by permission or status changes
 */
export default async function (db: DbService) {
    try {
        const schemaVersion = await db.getSchemaVersion();
        if (schemaVersion === 10) {
            console.info("Upgrading database schema from version 10 to 11");

            await db.processAllDocs([DocType.DeleteCmd], async (doc: any) => {
                if (!doc) return;

                // Only process DeleteCmds that are missing the language field and were not
                // generated by an actual deletion (the content document still exists)
                if (doc.language) return;
                if (doc.deleteReason === DeleteReason.Deleted) return;

                try {
                    const contentResult = await db.getDoc(doc.docId);
                    if (
                        contentResult.docs.length > 0 &&
                        contentResult.docs[0].type === DocType.Content
                    ) {
                        const contentDoc = contentResult.docs[0];
                        if (contentDoc.language) {
                            doc.language = contentDoc.language;
                            // Use insertDoc directly to preserve the existing updatedTimeUtc
                            await db.insertDoc(doc);
                        }
                    }
                } catch (error) {
                    console.error(
                        `Failed to backfill language for DeleteCmd ${doc._id} (docId: ${doc.docId}):`,
                        error,
                    );
                }
            });

            await db.setSchemaVersion(11);
            console.info("Database schema upgrade from version 10 to 11 completed successfully");
        } else {
            console.info(
                `Skipping schema upgrade v11: current version is ${schemaVersion}, expected 10`,
            );
        }
    } catch (error) {
        console.error("Database schema upgrade from version 10 to 11 failed:", error);
        throw error;
    }
}
