import { DocType, Uuid } from "../types";
import { IsNotEmpty, IsObject } from "class-validator";

/**
 * Document structure for client / CMS submitted changes to existing documents or new documents.
 * After successful processing, a differential "change" document (ChangeDto) is generated by the
 * API from the UpdateDto and distributed to clients.
 */
export class ChangeReqDto {
    @IsNotEmpty()
    docId: Uuid; // Uuid of submitted document in "doc" property
    @IsNotEmpty()
    type: DocType.ChangeReq;
    @IsObject()
    doc: any; // Object containing full submitted / updated document
}
