name: "Build & Deploy CMS to Production"

on:
  push:
    branches: [main]
    paths:
      - cms/**
      - .github/workflows/cms-deploy-production.yml
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

env:
  CI: true

jobs:
  test:
    uses: ./.github/workflows/cms-unit-tests.yml

  deploy:
    needs: test
    runs-on: [self-hosted, ac]
    environment: cms-production

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create .env file
        run: |
          touch .env
          echo VITE_AUTH0_CLIENT_ID=${{ secrets.VITE_AUTH0_CLIENT_ID }} >> .env
          echo VITE_AUTH0_DOMAIN=${{ vars.VITE_AUTH0_DOMAIN }} >> .env
          echo VITE_AUTH0_AUDIENCE=${{ vars.VITE_AUTH0_AUDIENCE }} >> .env
          echo VITE_APP_NAME=${{ vars.VITE_APP_NAME }} >> .env
          echo VITE_API_URL=${{ vars.VITE_API_URL }} >> .env
        working-directory: cms

      - name: Build Docker container
        run: docker build . -t ${{ vars.DOCKER_IMAGE }}
        working-directory: cms

      - name: Stop and remove old Docker container
        run: docker stop ${{ vars.DOCKER_CONTAINER }} || true && docker rm ${{ vars.DOCKER_CONTAINER }} || true

      - name: Run Docker container
        run: >
          docker run -d -p "${{ vars.DOCKER_PORT }}":80 
          --restart unless-stopped 
          --name=${{ vars.DOCKER_CONTAINER }} 
          ${{ vars.DOCKER_IMAGE }}
